apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl

spec:
  #To specify how this deployment should behave
  replicas: 1
  #Replicas is the number of pods we want to create
  selector:
    #Selector to tell the deployment to find all the different pod been created with the labels app:posts
    matchLabels:
      app: posts
  template:
    #Template is where we specify the exact configuration of a pod that we want the deployment  to create
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: crawan/posts:latest

---
apiVersion: v1
kind: Service
metadata:
  name: post-clusterip-srv
spec:
  ##type: NodePort
  selector:
    # posts , refer to the pod that we create in deployment, so we telling this service to find all the differnt pods with the label (posts) and expose this pods to the outside world
    app: posts
  ports:
    # Here we list out all the different ports we want to expose in the pod
    - name: posts
      # The name here just for login purposes
      protocol: TCP
      port: 4000
      # Represent Node service port
      targetPort: 4000
      # Represent pod port
